// Validates the ported gaze math two ways: the same properties the Python tests
// check, and a shared numeric fixture generated by the desktop implementation
// (test/make_parity_fixture.py), so the two pipelines are held to the same
// arithmetic, not merely to the same properties.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { ridgeFit, solve } from "../public/js/linalg.js";
import {
  HeadAwareModel,
  LEFT_EYE,
  RIGHT_EYE,
  crossValidatedError,
  eyeFeature,
  eyeOpenness,
  headPoseFromMatrix,
  medianSignal,
  signalsFromResult,
} from "../public/js/gaze.js";
import { selectDemoItems } from "../public/js/stimuli.js";

const close = (a, b, eps = 1e-9) => Math.abs(a - b) <= eps;

function eyeLandmarks(iris) {
  const lm = Array.from({ length: 478 }, () => ({ x: 0, y: 0 }));
  const [irisIdx, a, b, up, lo] = RIGHT_EYE;
  lm[a] = { x: 0.4, y: 0.5 };
  lm[b] = { x: 0.5, y: 0.5 };
  lm[up] = { x: 0.45, y: 0.46 };
  lm[lo] = { x: 0.45, y: 0.54 };
  lm[irisIdx] = { x: iris[0], y: iris[1] };
  return lm;
}

function rotate(lm, angle, [cx, cy]) {
  const c = Math.cos(angle), s = Math.sin(angle);
  return lm.map((p) => ({
    x: cx + (p.x - cx) * c - (p.y - cy) * s,
    y: cy + (p.x - cx) * s + (p.y - cy) * c,
  }));
}

function rotation4x4(yaw, pitch, roll) {
  const [cz, sz] = [Math.cos(roll), Math.sin(roll)];
  const [cy, sy] = [Math.cos(yaw), Math.sin(yaw)];
  const [cx, sx] = [Math.cos(pitch), Math.sin(pitch)];
  const rz = [[cz, -sz, 0], [sz, cz, 0], [0, 0, 1]];
  const ry = [[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]];
  const rx = [[1, 0, 0], [0, cx, -sx], [0, sx, cx]];
  const mul = (A, B) =>
    A.map((row, i) => B[0].map((_, j) => row.reduce((acc, _v, k) => acc + A[i][k] * B[k][j], 0)));
  const r = mul(mul(rz, ry), rx);
  const m = new Array(16).fill(0);
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) m[i * 4 + j] = r[i][j];
  m[15] = 1;
  return m;
}

const sig = (fx, fy, yaw = 0, pitch = 0, openness = 0.3) => ({ fx, fy, yaw, pitch, roll: 0, openness });

function gridSignals() {
  const out = [];
  for (let i = 0; i < 16; i++) {
    const fx = (i % 4) / 3, fy = Math.floor(i / 4) / 3;
    out.push(sig(fx, fy, (((i * 7) % 5) - 2) / 10, (((i * 11) % 5) - 2) / 10));
  }
  return out;
}

test("solve recovers a known linear system", () => {
  const x = solve([[2, 1], [1, 3]], [5, 10]); // 2x+y=5, x+3y=10 -> x=1, y=3
  assert.ok(close(x[0], 1) && close(x[1], 3));
});

test("ridgeFit shrinks towards a small-norm solution but keeps the bias", () => {
  const c = ridgeFit([[1, 0], [1, 1], [1, 2]], [1, 1, 1], 1e-9);
  assert.ok(close(c[0], 1, 1e-3) && close(c[1], 0, 1e-3));
});

test("eyeFeature values in the eye frame", () => {
  const [fx, fy] = eyeFeature(eyeLandmarks([0.46, 0.52]), RIGHT_EYE);
  assert.ok(close(fx, 0.6) && close(fy, 0.25));
});

test("eyeFeature is roll invariant", () => {
  const upright = eyeFeature(eyeLandmarks([0.47, 0.52]), RIGHT_EYE);
  const tilted = eyeFeature(rotate(eyeLandmarks([0.47, 0.52]), (25 * Math.PI) / 180, [0.45, 0.5]), RIGHT_EYE);
  assert.ok(close(tilted[0], upright[0]) && close(tilted[1], upright[1]));
});

test("eyeOpenness falls when the lid gap shrinks", () => {
  const open = eyeOpenness(eyeLandmarks([0.45, 0.5]), RIGHT_EYE);
  const closing = eyeLandmarks([0.45, 0.5]);
  closing[RIGHT_EYE[3]] = { x: 0.45, y: 0.499 };
  closing[RIGHT_EYE[4]] = { x: 0.45, y: 0.501 };
  assert.ok(eyeOpenness(closing, RIGHT_EYE) < open);
});

test("headPoseFromMatrix round-trips", () => {
  const { yaw, pitch, roll } = headPoseFromMatrix(rotation4x4(0.2, -0.15, 0.1));
  assert.ok(close(yaw, 0.2, 1e-6) && close(pitch, -0.15, 1e-6) && close(roll, 0.1, 1e-6));
});

test("HeadAwareModel compensates head pose", () => {
  const truth = (s) => [0.1 + 0.6 * s.fx + 0.3 * s.yaw, 0.1 + 0.6 * s.fy - 0.2 * s.pitch];
  const signals = gridSignals();
  const model = HeadAwareModel.fit(signals, signals.map(truth), 1e-9);
  const probe = sig(0.3, 0.7, 0.15, -0.1);
  const [px, py] = model.map(probe);
  const [ex, ey] = truth(probe);
  assert.ok(close(px, ex, 1e-3) && close(py, ey, 1e-3));
});

test("HeadAwareModel fits two poses with different gain", () => {
  // Each pose is held still (constant yaw/pitch), and head pose changes the gain of
  // the iris feature, not just an offset. An additive pose term adheres to one pose;
  // the pose-by-feature interaction terms fit both. The model must be accurate at
  // both calibrated poses, not only the last one.
  const truth = (s) => [
    0.1 + (0.5 + 1.0 * s.yaw) * s.fx + 0.3 * s.yaw,
    0.1 + (0.5 - 1.0 * s.pitch) * s.fy - 0.2 * s.pitch,
  ];
  const axis = [0.15, 0.5, 0.85];
  const signals = [];
  for (const [yaw, pitch] of [[0.0, 0.1], [0.5, -0.2]]) {
    for (const fy of axis) for (const fx of axis) signals.push(sig(fx, fy, yaw, pitch));
  }
  const model = HeadAwareModel.fit(signals, signals.map(truth), 1e-6);
  for (const [yaw, pitch] of [[0.0, 0.1], [0.5, -0.2]]) {
    const probe = sig(0.3, 0.7, yaw, pitch);
    const [px, py] = model.map(probe);
    const [ex, ey] = truth(probe);
    assert.ok(close(px, ex, 1e-2) && close(py, ey, 1e-2), `pose yaw=${yaw}: ${px},${py} vs ${ex},${ey}`);
  }
});

test("pose drift is zero within range and grows outside", () => {
  const model = new HeadAwareModel([], [], [(-5 * Math.PI) / 180, 0, 0], [(5 * Math.PI) / 180, 0, 0]);
  assert.ok(close(model.poseDriftDegrees(sig(0.5, 0.5, 0)), 0));
  assert.ok(close(model.poseDriftDegrees(sig(0.5, 0.5, (12 * Math.PI) / 180)), 7, 1e-6));
});

test("grouped cross-validation holds out a target's poses together", () => {
  const signals = [], targets = [], groups = [];
  for (const shift of [0, 0.12]) {
    gridSignals().forEach((s, i) => {
      signals.push({ ...s, yaw: s.yaw + shift });
      targets.push([0.1 + 0.6 * s.fx + 0.3 * (s.yaw + shift), 0.1 + 0.6 * s.fy]);
      groups.push(i);
    });
  }
  assert.ok(crossValidatedError(signals, targets, 1e-6, groups) < 0.05);
});

test("medianSignal is per-field median", () => {
  const m = medianSignal([sig(0, 1), sig(2, 3), sig(1, 5)]);
  assert.ok(close(m.fx, 1) && close(m.fy, 3));
});

test("signalsFromResult returns null without a face and a full signal with one", () => {
  assert.equal(signalsFromResult({ faceLandmarks: [] }), null);
  assert.equal(signalsFromResult({}), null);

  // Build a landmark set with both eyes laid out horizontally, iris centred.
  const lm = Array.from({ length: 478 }, () => ({ x: 0, y: 0 }));
  for (const spec of [RIGHT_EYE, LEFT_EYE]) {
    const [iris, a, b, up, lo] = spec;
    lm[a] = { x: 0.4, y: 0.5 };
    lm[b] = { x: 0.5, y: 0.5 };
    lm[up] = { x: 0.45, y: 0.46 };
    lm[lo] = { x: 0.45, y: 0.54 };
    lm[iris] = { x: 0.45, y: 0.5 };
  }
  const out = signalsFromResult({
    faceLandmarks: [lm],
    facialTransformationMatrixes: [{ data: rotation4x4(0.2, -0.1, 0.05) }],
  });
  assert.ok(close(out.fx, 0.5) && close(out.fy, 0));
  assert.ok(out.openness > 0);
  assert.ok(close(out.yaw, 0.2, 1e-6) && close(out.pitch, -0.1, 1e-6) && close(out.roll, 0.05, 1e-6));

  // Without a transformation matrix the pose falls back to zero.
  const flat = signalsFromResult({ faceLandmarks: [lm] });
  assert.ok(flat.yaw === 0 && flat.pitch === 0 && flat.roll === 0);
});

test("selectDemoItems keeps one member per pair, alternating condition", () => {
  const items = [];
  for (let p = 1; p <= 4; p++) {
    for (const cond of ["high", "low"]) {
      items.push({ id: `p0${p}${cond[0]}`, pair: `p0${p}`, condition: cond, text: "x" });
    }
  }
  const chosen = selectDemoItems(items);
  assert.equal(chosen.length, 4);
  assert.deepEqual(chosen.map((c) => c.condition), ["high", "low", "high", "low"]);
  // One item per pair, no adjacent same-frame repetition possible.
  assert.equal(new Set(chosen.map((c) => c.pair)).size, 4);
});

const PARITY = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), "fixtures", "parity.json"),
    "utf8",
  ),
);

test("the port reproduces the desktop implementation on a shared fixture", () => {
  const model = HeadAwareModel.fit(PARITY.signals, PARITY.targets, PARITY.ridge);
  for (let i = 0; i < PARITY.coeffs_x.length; i++) {
    assert.ok(close(model.coeffsX[i], PARITY.coeffs_x[i], 1e-8), `coeffsX[${i}]`);
    assert.ok(close(model.coeffsY[i], PARITY.coeffs_y[i], 1e-8), `coeffsY[${i}]`);
  }
  for (let i = 0; i < 3; i++) {
    assert.ok(close(model.poseLo[i], PARITY.pose_lo[i], 1e-12), `poseLo[${i}]`);
    assert.ok(close(model.poseHi[i], PARITY.pose_hi[i], 1e-12), `poseHi[${i}]`);
  }
  PARITY.probes.forEach((probe, i) => {
    const [nx, ny] = model.map(probe);
    assert.ok(close(nx, PARITY.mapped[i][0], 1e-8), `mapped[${i}].x`);
    assert.ok(close(ny, PARITY.mapped[i][1], 1e-8), `mapped[${i}].y`);
    assert.ok(
      close(model.poseDriftDegrees(probe), PARITY.drift_degrees[i], 1e-8),
      `drift[${i}]`,
    );
  });
  const cv = crossValidatedError(PARITY.signals, PARITY.targets, PARITY.ridge, PARITY.groups);
  assert.ok(close(cv, PARITY.cv_error, 1e-8), "cross-validated error");
});
